### PR TITLE
fix _fixupKey for composite keys to avoid "Internal Error in key fixu…

### PR DESCRIPTION
**Pull request by RyanLiu99**
…p - unable to locate entity"

### CODE REVIEW

**Comment by steveschmitt** [comment]
Awesome, thanks!  Do you have a test that demonstrates the problem?

**Comment by RyanLiu99** [comment]
I don't have a standalone test,  but I saw the problem and my fix works in the code in the project I am working on.

**Comment by steveschmitt** [comment]
Can you describe the situation and the entities involved?  Maybe I can add a test to our test suite.

**Comment by RyanLiu99** [comment]
Back end:
There are 3 tables/entities: A, B, and AB.   
Table A, B has Id column which is identity column in database.
Table AB has no Id column, rather it has  AId and BId columns which combined to make primary key for table AB and refers to  A.Id and B.Id respectively.

Table A is populated in database.

All entities are inherited from BaseEntity<T> which has T Id column. 

So table AB also has ID column but is [unmapped] to db.  
 public string Id {get return AId.ToString() + ":::"  + BId.ToString();} // breeze way

Front end:
The UI  is used to create entity AB and B together then submit to server to be saved to DB.

After submit changes to server, Breeze first fixes up temp key for entity B:  -1 -> B.Id from db. For example update temp Id -1 with real B.Id 555.  No problem.

Then it try to fix temp key for AB, let's say A.Id is 100, then it try to update  "100:::-1" -> "100:555".  When it does so, it cannot find "100:::-1" in index map and throws error "Internal Error in key fixup - unable to locate entity".  But "100:555" can be found in indexMap. I think it is because indexMap is already updated for AB when B is fixed up.

If I change B.Id implementation to
   public object Id { get {return new {AId, BId};}}  
then when it try to fix up key for AB, the tempValue -> realValue is  null -> null, which is worse. Java script cannot use object as key anyway.

**Comment by steveschmitt** [comment]
Ah, you are using a generated composite key.  Breeze supports native composite keys, like the database does, and we have tests for that, but we don't have tests for your scenario.

I'm curious, why did you decide to generate this string instead of using the native composite key?

**Comment by RyanLiu99** [comment]
What do you mean by "Breeze supports native composite keys"?  I know Breeze has good support of composite key on client side.  I think key map of tempValue-> realValue  is from server side. How those values are generated out of box in Breeze server?

Is that "Id" property special to Breeze, with it, will Breeze disregard composite key definition in Entity Framework ?  Id property is not needed for entity AB, not in database. Id comes from base entity which I will have hard time to get rid of (even I don't think it is good idea to have it in base class). 

I will investigate more. 

|Thanks!

**Comment by RyanLiu99** [comment]
I dig more into this issue. We have extra layer on top of breeze. The problem in on our side.  So my changes in this pull request is not necessary, but might good to have too, e.g.  if old value and new value are same, really no need to do key fix up.

**Pull request closed without merging**
