### PR TITLE
AMD corrections

### PR DESCRIPTION
**Pull request by Lukino2000**
Hi, as per PR #73 I changed like you said my source and after some other test i notice another Uncaught ReferenceError in breeze.dataService.webApi.js (AutoGeneratedKeyType). so this contains all changes.
I'm relatively new to git and github world so, please, excuse me for any error.

### CODE REVIEW

**Comment by wardbell** [comment]
AARGH!  I made all of these changes yesterday myself ... committed them locally ... and forgot to push them to github. My bad. It's done. 

Closing your PR.

**Comment by Lukino2000** [comment]
you forgot Uncaught ReferenceError in breeze.dataService.webApi.js (AutoGeneratedKeyType)

**Comment by wardbell** [comment]
Didn't forget because I didn't know about it!  Apparently we had undeclared references to a number of variables in the adapters that only just made available independently of breeze.debug.js. Thanks for catching this. Still a work in progress. Committed. Try again please.

**Comment by Lukino2000** [comment]
ok, at the moment it seem working. keep in mind I use this configuration and so i did not test other adapters

        breeze.config.initializeAdapterInstances({
          dataService: "webApi",
          modelLibrary: "ko",
          ajax: "jQuery",
          uriBuilder: "odata"
        });

**Pull request closed without merging**
