### PR TITLE
Add support for none scalar values to maxLength validator

### PR DESCRIPTION
**Pull request by fdmota**
I am not sure if there is a better way of doing this or if there a reason behind how it is now but maxLength does not work when isScalar is false.
My metadata looks like this and maxLength fails.

        {
          "name": "adminEmail",
          "dataType": "String",
          "isScalar": false,
          "maxLength": 24,
          "defaultValue": [],
          "validators": [
            {
              "name": "maxLength",
              "maxLength": 24
            }
          ]
        }

I could have solved the problem with a custom validator but why?
I suspect other validators suffer from the same problem.

### CODE REVIEW

**Comment by steveschmitt** [comment]
Thanks, that's a good idea.  But until I looked at the code, I thought maxLength would validate the length of the array.

**Comment by fdmota** [comment]
Indeed there is a few possible scenarios around the maxLength concept. Here I was think maxLength in the context of the primitive dataType which is string. arrayMaxLength or arrayMinLength are also interesting validators.

**Comment by steveschmitt** [comment]
Looks like you are doing something with array sorting.  What is this "uniqueKey" property?

**Comment by fdmota** [comment]
Only my first commit should be part of this pull request. I need to remove the other commits. 

I need breeze to support navigation properties sorting. It is working for me but it is only partially abstracted. All my entities have the primary key called uniqueKey and did not want to go deeper in  abstracting it for now.

**Comment by steveschmitt** [comment]
Ah, I see.  Be cautious also about changing nextNumber and nextNumberIncrement.  They are used by Breeze for generating temporary keys when entities are created on the client.

**Comment by fdmota** [comment]
I have changed  nextNumber and nextNumberIncrement for the project where I am using breeze. The backend is using unsign int64. From 0 to unsign int32, keys are considered local. SInce the key has a validator that force values to be > 0, I decided to change the autogenkey internals to suit my needs.

**Pull request closed without merging**
